### ISSUE TITLE
Admin dashboard 

### ISSUE THREAD

**Issue by preciousimo** [preciousimo/studybud#1]
Please someone should work on the admin dashboard. Search online for whatever module you could use to twerk Django admin dashboard.

**Comment by preciousimo** [comment]
Your can check up jazzmin

**Comment by JolomonSon** [comment]
Okay.. I've checked up jazzmin theme and I should be able to use it for the admin dashboard

**Comment by JolomonSon** [comment]
Django Admin Thene Implemented

**Comment by preciousimo** [comment]
John you did a great work on the admin dashboard. 💪
